#!/bin/bash

set -e

CONTAINER_REPO=shiftcrypto/firmware_v2
CONTAINER_VERSION=$(cat .containerversion)

if [[ $# -gt 0 ]]; then
    CONTAINER_REPO=$(echo $1 | tr '[:upper:]' '[:lower:]')
fi

if [[ $# -gt 1 ]]; then
    CONTAINER_VERSION=$2
fi

docker build --pull --no-cache -t $CONTAINER_REPO:latest -t $CONTAINER_REPO:$CONTAINER_VERSION .
