#!/bin/bash

set -e

if [[ $# -gt 0 ]]; then
    CONTAINER_REPO=$1
fi

if [[ $# -gt 1 ]]; then
    CONTAINER_VERSION=$2
fi

docker build --pull --no-cache -t $CONTAINER_REPO:latest -t $CONTAINER_REPO:$CONTAINER_VERSION .
