#!/bin/bash

set -e

CONTAINER_REPO=$(echo $1 | tr '[:upper:]' '[:lower:]')
CONTAINER_VERSION=$(cat .containerversion)

docker push $CONTAINER_REPO:latest
docker push $CONTAINER_REPO:$CONTAINER_VERSION
