[package]
name = "bitbox-boot-utils"
version = "0.1.0"
edition = "2024"

[lib]
test = false
doctest = false

[features]
board-stm32u5-dk = ["bitbox03-memory/board-stm32u5-dk"]

[dependencies]
bitbox03-memory = { path = "../bitbox03-memory" }
cortex-m = { workspace = true }
sha2 = { workspace = true }
p256 = { version = "0.13.2", default-features = false, features = ["arithmetic", "ecdsa"] }
