# See reference docs at
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Development container
on:
  workflow_call:
    inputs:
      publish-container:
        default: false
        required: false
        type: boolean
    outputs:
      container-version:
        value: ${{ jobs.dev-container.outputs.container-version }}

jobs:
  dev-container:
    runs-on: ubuntu-22.04
    outputs:
      container-version: ${{ steps.version.outputs.version }}
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Get version
        id: version
        run: echo version=$(cat .containerversion) >> $GITHUB_OUTPUT

      - name: Check if container should be published
        id: checks
        run: echo container-published=$(./.ci/check-container-version-published) >> $GITHUB_OUTPUT

      # On PR builds we will build an image and tag it with `pr-<PR-NUMBER>` if a new image should be tested
      - name: Build container
        if: steps.checks.outputs.container-published == 'false'
        env:
          REPO: ${{ github.event_name == 'pull_request' && format('ghcr.io/{0}', github.repository) || 'shiftcrypto/firmware_v2' }}
          VERSION:  ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || steps.version.outputs.version }}
        run: |
          repo=$(echo $REPO | tr '[:upper:]' '[:lower:]')
          docker build -t $repo:latest -t $repo:$VERSION .

      - name: Login to Github Container Registry
        if: github.event_name == 'pull_request' && steps.checks.outputs.container-published == 'false'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        if: github.event_name == 'push' && steps.checks.outputs.container-published == 'false'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Publish container
        if: steps.checks.outputs.container-published == 'false'
        env:
          REPO: ${{ github.event_name == 'pull_request' && format('ghcr.io/{0}', github.repository) || 'shiftcrypto/firmware_v2' }}
          VERSION:  ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || steps.version.outputs.version }}
        run: |
          repo=$(echo $REPO | tr '[:upper:]' '[:lower:]')
          docker push $repo:latest
          docker push $repo:$VERSION
          echo version=pr-${{ github.event.number }} >> $GITHUB_OUTPUT

      - name: PR container version
        if: github.event_name == 'pull_request' && steps.checks.outputs.container-published == 'false'
        env:
          VERSION:  ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) }}
        run: echo version=pr-${{ github.event.number }} >> $GITHUB_OUTPUT
