# See reference docs at
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Default branch ci
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  linux-docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive
      - name: Pull CI container image
        run: ./.ci/pull-container
      - name: Run CI in container
        env:
          COMPARE_REV: ${{ github.event.before }}
        run: ./.ci/run-container-ci ${{github.workspace}}
