# See reference docs at
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Default branch ci
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive

      - name: Check if container should be published
        id: checks
        run: ./.ci/check-container-version-published >> $GITHUB_OUTPUT

      - name: Set up QEMU for Docker
        if: steps.checks.outputs.container-published == 'false'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: docker-image
        if: steps.checks.outputs.container-published == 'false'
        uses: docker/setup-buildx-action@v3

      - name: Build container
        env:
          BUILDX_BUILDER: ${{ steps.docker-image.outputs.name }}
        if: steps.checks.outputs.container-published == 'false'
        run: ./.ci/build-container

      - name: Publish container
        if: steps.checks.outputs.container-published == 'false'
        run: ./.ci/publish-container

      - name: Pull CI container image
        run: ./.ci/pull-container

      - name: Run CI in container
        env:
          COMPARE_REV: ${{ github.event.before }}
        run: ./.ci/run-container-ci ${{github.workspace}}
