on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - Dockerfile
jobs:
  check-base-image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Publish new container version
        run: ./.ci/publish-container
